export let graph = {
'polkadot': 'polkadot-new',
'theta network': 'theta',
'celsius network': 'celsius',
'crypto.com coin': 'crypto-com-coin',
'cusdc': 'usd-coin',
'ceth': 'nxm',
'dai': 'multi-collateral-dai',
'leo token': 'unus-sed-leo',
'yearn.finance': 'yearn-finance',
'sushi': 'sushiswap',
'cdai': 'compound-dai',
'near': 'rlc',
'elrond': 'elrond-egld',
'the graph': 'noia-network',
'omg network': 'omg',
'terra': 'terra-luna',
'reserve rights token': 'reserve-rights',
'aave link': 'c20',
'iost': 'iostoken',
'nexus mutual': 'rlc',
'bitcoin cash abc': 'c20',
'empty set dollar': 'nxm',
'aave eth': 'c20',
'terrausd': 'theta',
'1inch': 'nxm',
'bancor network token': 'bancor',
'gnosis': 'gnosis-gno',
'cusdt': 'yearn-finance',
'aave usdc': 'nxm',
'aave [old]': 'celsius',
'frax': 'omg',
'dynamic set dollar': 'xdai',
'golem': 'c20',
'cuni': 'celsius',
'kava.io': 'theta',
'kucoin token': 'kucoin-shares',
'keeperdao': 'c20',
'derivadao': 'omg',
'staked ether': 'aelf',
'injective protocol': 'c20',
'alpha finance': 'exrnchain',
'dfi.money': 'yearn-finance',
'iexec rlc': 'rlc',
'oasis network': 'theta',
'c0x': 'nxm',
'skale': 'nxm',
'zero collateral dai': 'terra-krw',
'syntropy': 'noia-network',
'xinfin': 'xinfin-network',
'btc standard hashrate token': 'rlc',
'api3': 'celsius',
'yusd': 'exrnchain',
'coinmetro': 'coinmetro-token',
'nucypher': 'bancor',
'aave tusd': 'theta',
'keep3rv1': 'yearn-finance',
'firo': 'celsius',
'terrakrw': 'terra-krw',
'tbtc': 'c20',
'elf': 'aelf',
'wrapped nxm': 'nxm',
'fetch.ai': 'fetch',
'efforce': 'bancor',
'defipulse index': 'defichain',
'e-radix': 'exrnchain',
'travala.com': 'travala',
'xdai stake': 'xdai',
'hive': 'hive-blockchain',
'lbry credits': 'library-credit',
'crypto20': 'c20',
'basis cash': 'yearn-finance',
'adex': 'adx-net',
'frax share': 'theta',
'haven': 'haven-protocol',
'cvault.finance': 'bigbang-core',
'tokenlon': 'indorse-token',
'i/o coin': 'iocoin',
}